### ISSUE TITLE
Can't get terraboard running locally (without docker)

### ISSUE THREAD

**Issue by number5** [camptocamp/terraboard#1]
So I run `go get https://github.com/camptocamp/terraboard`
and the `go install .` compiled and installed it.

With following env variables set
```
AWS_SECRET_ACCESS_KEY=1xxxxxx
AWS_ACCESS_KEY_ID=AKIAJMCDDREEFEEDE
AWS_REGION=ap-southeast-2
AWS_BUCKET=blah-tfstates
```

```
λ terraboard                                                             
INFO[0000] Automigrate
INFO[0000] New db is &{<nil> <nil> 0 0xc42024c3c0 false 2 {0xc42022c910} <nil> map[] 0xc42013f830 0x4c25160 0xc42025a560 false}
INFO[0000] Refreshing DB from S3
```
But running terraboard only create a sqlite db then quit.

What have I done wrong?

**Comment by raphink** [comment]
That is most certainly because Terraboard tries to listen on port 80 and you don't have the privileges for that. You could try to run it with `sudo`.

I will go ahead and change the port to `8080` instead.

**Comment by raphink** [comment]
For the record, I made the port configurable in fc4eaef487cddf20b6cef90a581c750606f58eb7 (see `./terraboard -h`).
