### ISSUE TITLE
Feat: Display map type attributes in an easier to read format

### ISSUE THREAD

**Issue by mhaley-miovision** [camptocamp/terraboard#101]
As it stands in the UI today map values appear as a single line in the table of values.
![image](https://user-images.githubusercontent.com/12234439/88214780-b5dae080-cc28-11ea-9f5e-ef98315eb8aa.png)

This is not an easy to read format for large maps of values.  We should try to "pretty print" these values, or parse the maps and present them in the table as separate values.  For example, using the screenshot above as a reference, we could have

| Attribute                        | Value                                 |
|--------------------------------|------------------------------------|
| id                                   | "8591566720176406857" |
| triggers.index                | 4                                        |
| triggers.tf_stack_name | "terraboard_develop"        |
| triggers.value1              | "val 1"                                |
| triggers.value2              | "val 2"                                |
| triggers.value3              | "val 3"                                |

**Comment by raphink** [comment]
This shouldn't be too hard in angular I think
