### ISSUE TITLE
Panic at start with 0.22.0

### ISSUE THREAD

**Issue by jimsheldon** [camptocamp/terraboard#105]
Hello!

I just attempted an update to 0.22.0 and received a panic on startup:

```
time="2020-08-14T19:51:13Z" level=info msg="Terraboard v0.22.0 (built for Terraform v0.13.0) is starting..."
panic: terraform.io/builtin/terraform is not a legacy addrs.Provider
```

Has 0.22.0 dropped support for state file versions older than 0.13.0?  This issue describes a similar error which may have been fixed in newer versions of the module? https://github.com/hashicorp/terraform/issues/25803

**Comment by raphink** [comment]
That is unfortunately possible. I'll try to investigate this, but I did have to patch that part in order to support Terraform 0.13, so I wouldn't be too surprised if the Terraform 0.13 libraries dropped support for older statefile formats...

**Comment by dmonaco05** [comment]
I had to use 0.21.0 due to this issue
