### ISSUE TITLE
Using terraboard on local environment

### ISSUE THREAD

**Issue by razielvamp** [camptocamp/terraboard#106]
Can I use terraboard on local server without AWS infrastructure?

I trying to create local environment like:
Minio (instead S3)
MongoDB (instead DocumentDB)
PostgreSQL (instead RDS PSQL)

API of those services are pretty close to original ones.

1. How can I override S3 endpoint URL and port (for example http://127.0.0.1:1234/bucket_name)
2. How can I set MongoDB URL and port (127.0.0.1:27017)
3. Looks like Terraform Cloud is not necessary requirement if I plan to use only local resources?

**Comment by raphink** [comment]
Terraform Cloud is never a requirement. Minio should work with `--aws-endpoint=`, not sure about MongoDB though.
