### ISSUE TITLE
Unable to start terraboard in Docker following Readme instructions 

### ISSUE THREAD

**Issue by uritau** [camptocamp/terraboard#123]
First of all, thanks for your amazing work with terrabord!!!!
An absolutely amazing project 💙 
But trying to follow Readme instructions with docker I haven't been able to have an up and running environment, I needed to change to docker-compose "way".

**Comment by uritau** [comment]
Solved in PR #124

**Comment by raphink** [comment]
Thanks for closing this @uritau
