### ISSUE TITLE
Disable versioning

### ISSUE THREAD

**Issue by mong0520** [camptocamp/terraboard#125]
It's a cool tool and I'd like to know if it is possible to disable S3 versioning scan?
Because our tfstate file has many many version on S3 and I only like to see the latest version on the chart.

**Comment by raphink** [comment]
Not at the moment. Versioning is essential to retrieve the history of each tfstate in Terraboard.

**Comment by mong0520** [comment]
I understanding Versioning is essential retrieve the history of each tfstate.
However sometimes I'd like to have a quick and latest view/dashboard of m tfstate of a complex infrastructure which stored a lots of version on S3. Then that will be great if the cool tool can provide a flag (default: true) to disable versioning.
Just a suggestion :D
