### ISSUE TITLE
Display outputs for state file

### ISSUE THREAD

**Issue by mong0520** [camptocamp/terraboard#126]
I understand that the dashboard can show attributes of a tfstate file, but is it possible to show `outputs` as well?
Sometimes we have customized outputs and it will be great if I can see output from the dashboard

**Comment by raphink** [comment]
Yes, I had started working on outputs a while ago (https://github.com/camptocamp/terraboard/pull/51) but never finished the PR.

**Comment by hoshsadiq** [comment]
@raphink if you don't mind, I'd be happy to try and take your PR and rebase and potentially fix it.
