### ISSUE TITLE
support of terraform 0.14.3

### ISSUE THREAD

**Issue by xinity** [camptocamp/terraboard#137]
just wondering how to help to support newer version of terraform? 

any plans to support 0.14.3 perhaps ?

let me know if I can help

Regards

**Comment by mihaiplesa** [comment]
There is support for `0.14.5` in but someone needs to perform a release. @raphink let me know if I can help.

**Comment by raphink** [comment]
I'll plan a release asap.

**Comment by raphink** [comment]
Just released v1.0.0 https://github.com/camptocamp/terraboard/releases/tag/1.0.0
