### ISSUE TITLE
GCP support

### ISSUE THREAD

**Issue by aamarques** [camptocamp/terraboard#143]
How can I configure terraboard to get tfstate from GCS ?
Someone with an example ?

Cheers,

**Comment by nikkaravias-hopper** [comment]
Have you tried using the GCP specific variables presented in the documentation?

`

--gcs-bucket | N/A | gcp.gcs-buckets | Google Cloud Storage buckets to access | -
-- | -- | -- | -- | --
--gcp-sa-key-path | GCP_SA_KEY_PATH | gcp.gcp-sa-key-path | Path to the service account key to use for Google Cloud Storage

`

**Comment by aamarques** [comment]
> Have you tried using the GCP specific variables presented in the documentation?
> 
> `
> 
> --gcs-bucket	N/A	gcp.gcs-buckets	Google Cloud Storage buckets to access	-
> --gcp-sa-key-path	GCP_SA_KEY_PATH	gcp.gcp-sa-key-path	Path to the service account key to use for Google Cloud Storage	
> `

Yep I did and forgot to close this.
