### ISSUE TITLE
advice on postgresql minimal requirement for terraboard? [doc]

### ISSUE THREAD

**Issue by Grummfy** [camptocamp/terraboard#144]
Hello,
it could be nice to have a requirement for the postgresql db.

thanks

**Comment by raphink** [comment]
Do you mean a minimal version?

Terraboard doesn't use any specific PostgreSQL extension, so any version that I'm aware of should work.

If you do encounter versions that are not supported, feel free to report them and we can document it.

**Comment by Grummfy** [comment]
thanks
