### ISSUE TITLE
Static files not part of release

### ISSUE THREAD

**Issue by nishkrishnan** [camptocamp/terraboard#146]
Hi, we use our own container management system so we can't use the docker configuration provided in the repo.

Wondering what the guidance is here, I'm installing a given release using curl but obviously just that isn't enough since the static files aren't included. Is there anyway to include them or do I just have to clone the repository at the given release to get the static content.

**Comment by raphink** [comment]
I don't know what you mean by your "own container management system", but I'm confident there must be a way to get an equivalent of the provided `Dockerfile`.

That said, it could be interesting at some point to build the static files inside the binary using https://github.com/rakyll/statik for example. I'd welcome a PR for that.
