### ISSUE TITLE
Problem with example startup script

### ISSUE THREAD

**Issue by Jaff** [camptocamp/terraboard#150]
I made a startup shell script based on the "Launch with Docker" example, and having problems. First of all, the last line of the postgres section ends with '-d' and that yields the error message in the log:
```
postgres: option requires an argument -- 'd'
Try "postgres --help" for more information.
```
Then, eliminating that, I try to start the terraboard image and see:
```
time="2021-04-14T22:54:33Z" level=info msg="Terraboard v1.1.0-1-g902a2a1 (built for Terraform v0.14.10) is starting..."
time="2021-04-14T22:54:33Z" level=info msg="Using AWS (S3+DynamoDB) as the state/locks provider"
time="2021-04-14T22:54:33Z" level=fatal msg="pq: SSL is not enabled on the server"
```
Running this on MacOS 10.15.7

**Comment by raphink** [comment]
Thanks for that report. I just realized the Docker example, which I suppose is what you are referring to, wasn't fixed when the README was.
