### ISSUE TITLE
Support Kubernetes Deployment

### ISSUE THREAD

**Issue by azhar22k** [camptocamp/terraboard#154]
GIven it is a dockerized project, pretty easy to deploy on K8S as well with the right configurations.
I have done it my self but IMO should be supported as out of the box as well.

**Comment by azhar22k** [comment]
I'm willing to do it, questions how should it be done

- Basic kubectl and SHell commands
- A helm chart
- Something else?

**Comment by mcanevet** [comment]
I guess Helm Chart could be great.

**Comment by raphink** [comment]
We have a helm chart at https://github.com/camptocamp/charts/tree/master/terraboard

**Comment by azhar22k** [comment]
Ohh. Never saw that.
Would be good to add a deployment step for them in the Readme of this repo for a better visibility

**Comment by mcanevet** [comment]
@raphink maybe we should move it to this project. A lot of projects are providing `Dockerfile`, `docker-compose` and `Helm` chart in the same git repository nowadays.

**Comment by raphink** [comment]
I'll try to find time to rappatriate the helm chart here. Unless @hbollon is interested in doing it 😁

**Comment by raphink** [comment]
I think for now we can simply add a doc in the README on how to instantiate the chart from camptocamp.github.io
