### ISSUE TITLE
New version of terraform (1.0) ?

### ISSUE THREAD

**Issue by Grummfy** [camptocamp/terraboard#166]
Hello,
terraform 1.0 is out, do you know when you plan to support it?

thanks

**Comment by raphink** [comment]
Unfortunately, Terraform 1.0.0 has removed a core library for Terraboard in https://github.com/hashicorp/terraform/commit/f40800b3a43851bbbbb98adff9e4eeab0fb575ca

We need to think of a solution.

**Comment by raphink** [comment]
#185 will support Terraform v1.0.2

**Comment by Grummfy** [comment]
thanks
