### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by weeclemans** [camptocamp/terraboard#235]
After launching the two docker containers, I open the link http://localhost:8080/ in my browser and get a "404 page not found" error.  A query to /api/plans answers
``` {"page":0,"plans":[],"total":0} ```

 Please help me.

```
# ./terraboard_v2.1.1 --log-level debug
INFO[0000] Terraboard v2.1.1 (built for Terraform v1.0.2) is starting...
INFO[0000] Using AWS (S3+DynamoDB) as state/locks provider
INFO[0000] Automigrate
DEBU[0000] gorm.io/driver/postgres@v1.1.0/migrator.go:2342.539368-SELECT count(*) FROM INFORMATION_SCHEMA.columns WHERE table_schema = CURRENT_SCHEMA() AND table_name = 'states' AND column_name = 'lineage'
DEBU[0000] Total providers: 1
INFO[0000] Refreshing DB
DEBU[0000] Listing states from S3                        bucket=tf-state-sandbox prefix=
DEBU[0000] Listening on port 8080
INFO[0000] Serving swagger on port 8081
DEBU[0000] Found states from S3                          bucket=tf-state-sandbox prefix= states=1
DEBU[0000] github.com/camptocamp/terraboard/db/db.go:4183.492806-SELECT states.path, versions.version_id FROM "states" JOIN versions ON versions.id = states.version_id
DEBU[0001] Version is already in the database, skipping  version_id=EO4DuwqVfAq3bKiwCC4S63_VkFqPsl3e
DEBU[0001] State is already in the database, skipping    path=sandbox/s3/terraform.tfstate version_id=EO4DuwqVfAq3bKiwCC4S63_VkFqPsl3e
DEBU[0001] Waiting 1 minutes until next DB sync
```

**Comment by hbollon** [comment]
Hi @weeclemans,
Sorry for the late answer, I doesn't achieve to reproduce your issue.

In my opinion the problem does not come from Terraboard but from a bad configuration on your side.
Furthermore, it's totally normal that you do not have any data on the `/api/plan` endpoint if you doesn't send any plan to Terraboard (cf. [How to push plans to Terraboard](https://github.com/camptocamp/terraboard#push-plans-to-terraboard)).
In line with your logs, however, you should have states. You can try requesting the api on the `/lineages/stats` endpoint.

However send me more information about your situation anyway like: your OS and its version, docker commands executed, etc.

**Comment by automaticgiant** [comment]
similar issue for me
i downloaded the darwin amd64 binary and ran
no web assets found, including /static/favicon.ico
api endpoints seem to work fine from swagger port
should this be supported?
i'll try the container at some point. seems to work in-container. what's this about?

looking at https://github.com/camptocamp/terraboard/blob/master/Dockerfile, i guess it wouldn't work without the container so that's probably @weeclemans' issue as well
