### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [camptocamp/terraboard#245]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@afkl-cuit) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by hbollon** [comment]
Hello @JamieSlome !
Thanks for contacting us. 
We have ongoing internal discussions about this issue (security task force).
Let us organize ourself and we will come back to you when we have a clearer vision of the responsibilities. 
Regards,

**Comment by JamieSlome** [comment]
@hbollon - appreciate the follow-up 👍
