### ISSUE TITLE
Is Support for HTTP Backend Planned?

### ISSUE THREAD

**Issue by Dan6erbond** [camptocamp/terraboard#256]
I've been looking at this project, as it looks super interesting for a selfhosted Terraform solution, but currently since I'm not sure if I will be using S3 buckets or an HTTP backend like [terraform-http-backend](https://pkg.go.dev/github.com/markcaudill/terraform-http-backend) for my state, I was wondering if support for the HTTP backend is planned? Thanks!

**Comment by hbollon** [comment]
Hi @Dan6erbond, sorry for the delay.
It's actually not a planned feature on our side, I personally don't have much time to do new features on Terraboard atm, however it's an interesting one so we may consider that in the future.
That said, if someone is interested to make a PR for that I would be happy to help :+1:
