### ISSUE TITLE
All Paths Redirect to Frontend

### ISSUE THREAD

**Issue by Dan6erbond** [camptocamp/terraboard#260]
Hi, I tried deploying Terraboard to Kubernetes today, with a Traefik Ingress. When I go to https://terraboard.example.com/ I see the Terraboard frontend, but it isn't able to load any data from the API. So I tried going to https://terraboard.example.com/api/user and just got redirected back to the frontend again. 

I used Terraform to deploy Terraboard, but the config should match up with the Helm chart. This seems to be an issue with the configuration of the server, though I'm not sure why.

**Comment by Dan6erbond** [comment]
Not quite sure what was causing it, but the issue is gone now.

**Comment by mahaffey** [comment]
I am also seeing this issue any pointers?

Thank you
