### ISSUE TITLE
Local state files?

### ISSUE THREAD

**Issue by Bekt** [camptocamp/terraboard#33]
Hello, this project looks great. Are there any plans to support local state files?

**Comment by raphink** [comment]
I don't have plans for that personally, but I'm open to adding new backends if you want to provide a PR.

Terraboard stores states by version. When using S3, this is done by using a versioned bucket and storing the bucket versions in the DB. With a local backend, I'm not sure how that would work, but maybe the creation/modification epoch or state serial could be used as the version.
