### ISSUE TITLE
Error when doing a go get

### ISSUE THREAD

**Issue by utshav2008** [camptocamp/terraboard#36]
```
Fri Sep 15:~/terraboard:~go get -u -v github.com/camptocamp/terraboard

../src/src/github.com/hashicorp/terraform/config/testing.go:9: t.Helper undefined (type *testing.T has no field or method Helper)

I went inside the source and did a 'go build' and could see similar issues

src/github.com/camptocamp/terraboard:~go build .
# github.com/hashicorp/terraform/config
../../../src/github.com/hashicorp/terraform/config/testing.go:9: t.Helper undefined (type *testing.T has no field or method Helper)
```

Can you please help me with this.

**Comment by Evesy** [comment]
Getting the same here too

**Comment by cryptobioz** [comment]
It looks like you do not have the last version of Go, using the version 1.9 should solve this bug.

**Comment by raphink** [comment]
This is because of a change in the Terraform code. For now, I have fixed this by setting the version of Terraform used in the dependencies. You can build Terraboard by using the proper versions, using [dep](https://github.com/golang/dep):

```
$ dep ensure
$ go build .
```

**Comment by raphink** [comment]
`go get` now works (at least with latest go).

One way to fix this would be to commit the `vendor/` directory into the repository, but I'm not a big fan of that…
