### ISSUE TITLE
The overview list is useless with 1-20 / 3477 currently on our instance

### ISSUE THREAD

**Issue by ckaenzig** [camptocamp/terraboard#4]
I'm not sure how it's meant to be used, but it seems the only way to find the path I want would be to scroll through the 173 pages of entries. I think there should be some form of searching in there (for paths, not resources).

**Comment by raphink** [comment]
I have now reorganized the overview to list each path only once and display only the most recent version, sorted by version. On our instance, this lists 118 paths (6 pages), which is already a bit better.

To view a specific path, you can always select it directly from the select list on top of the page, where you can type the path.

I plan on adding a filter on top of the path list in the overview if that would help.
