### ISSUE TITLE
Don't know how to install & run

### ISSUE THREAD

**Issue by arocki7** [camptocamp/terraboard#44]
Hi,

I'm sorry to say this - I tried all day long and couldn't figure out how to install the software and make it work.

Tried with go and docker - still, no luck.

Thanks.

**Comment by mcanevet** [comment]
Doesn't this work for you?
https://github.com/camptocamp/terraboard#use-with-docker

**Comment by arocki7** [comment]
I tried it this morning with the following commands. It worked.

docker run --name db -e POSTGRES_USER=gorm -e POSTGRES_PASSWORD=mypassword -e POSTGRES_DB:gorm -d --restart=always postgres

docker run -d -p 8080:8080 -e AWS_REGION=eu-west-1 -e AWS_ACCESS_KEY_ID=xxx -e AWS_SECRET_ACCESS_KEY=xxx -e AWS_BUCKET=xxx -e AWS_DYNAMODB_TABLE=xxx -e DB_PASSWORD=mypassword --link postgres:db --restart=always --name terraboard camptocamp/terraboard:latest

I actually thought we can create and manage terraform.
