### ISSUE TITLE
Http server only listening on IPV6, but didn't work  for ipV4

### ISSUE THREAD

**Issue by gotojeffray** [camptocamp/terraboard#47]
Hi there,

I sucessfully run the terraboard from source, but found that it's only listening on ipv6.
output from netstat:
tcp6       0      0 :::8080                 :::*                    LISTEN      3140/./terraboard

so it doesn't work for http://ipv4:8080. 

Could you help me to solve that?

**Comment by ijnuemik** [comment]
Having the same experience. Is it solved?

**Comment by raphink** [comment]
Sorry, I'm unable to reproduce this at the moment.

**Comment by socar-isabel** [comment]
Sorry.. It was a problem of my Helm chart.
Thank you for your reply.

**Comment by ijnuemik** [comment]
Sorry.. It was a problem of my Helm chart.
Thank you for your reply.

**Comment by raphink** [comment]
Thanks for commenting @ijnuemik
