### ISSUE TITLE
Feature request: multiple s3 buckets

### ISSUE THREAD

**Issue by kshcherban** [camptocamp/terraboard#48]
Would be nice to have support for multiple s3 buckets for large terraform installations.

**Comment by raphink** [comment]
This is an interesting idea, and I'd welcome a PR for that!

**Comment by fivehorizons** [comment]
agree!  We have 8-12 accounts in AWS org  and using independent buckets for state

**Comment by fivehorizons** [comment]
Could this be overcome by having multiple terraboard containers using the same PostgresDB?   @kshcherban

**Comment by m00lecule** [comment]
Could this issue be reopened? Terraboard is missing key feature

**Comment by Shocktrooper** [comment]
Agreed. most terraform setups do not use a single state backend

**Comment by fivehorizons** [comment]
I was able to overcome this having a container for each account pointing them to same database and data was aggregated

**Comment by mcanevet** [comment]
fixed by #177
