### ISSUE TITLE
GCP & Azure support

### ISSUE THREAD

**Issue by sagivle** [camptocamp/terraboard#56]
are you planing adding support for GCP and Azure?

**Comment by raphink** [comment]
We don't have that need at the moment, but I'd welcome a contributions for it.

**Comment by raphink** [comment]
Note: now that support for TFE was added in #67, it should be easier to add support for GCP and Azure.

**Comment by fr34k8** [comment]
@raphink GCP would be awesome!

**Comment by tristanvanthielen** [comment]
@sagivle, @fr34k8, @raphink  I have just opened a pull request adding GCS support #91 . Please check it out and let my know if you find any issues or have any insights with regards to improving implementation!
