### ISSUE TITLE
Does not work with AWS cross-account assumed role

### ISSUE THREAD

**Issue by dimisjim** [camptocamp/terraboard#57]
Hi. 

I have my cli configured with its token id and secret key. It has permission to assume a role in another AWS account, where the s3 bucket and dynamo table are located. 

How do I configure terraboard for this setup? Simply passing `AWS_SECRET_ACCESS_KEY` and
`AWS_ACCESS_KEY_ID` of the linked account to the terraboard image does not work of course.

The goal here is to have one terraboard showcasing multiplestate files from multiple aws accounts. That would require setting multiple dynamodb tables. Is this possible?

Thanks in advance.

**Comment by dimisjim** [comment]
Setting proper policies in the bucket (bucket full owner access) makes all state files viewable.

There is still a need for multiple dynamodb tables input, for terraboard to check multiple lock states.

**Comment by raphink** [comment]
@dimisjim 	you can use a single table for multiple states.

**Comment by dimisjim** [comment]
@raphink Correct me if I am wrong, but DynamoDB tables as far as I know have no global unique arn like s3 buckets. This means that I have to create every DynamoDB table in each AWS account, for tf backend to see it

```
backend "s3" {
    ...
    ...
    dynamodb_table = "nameOfTableInTheSameAccount" }
```

Btw, MFA is enabled in IAM.

**Comment by fivehorizons** [comment]
@dimisjim Did you find a solution for assumed Roles?

**Comment by dimisjim** [comment]
@fivehorizons No

**Comment by fivehorizons** [comment]
> @fivehorizons No

Thanks for reply.   I am trying to use ECS and parameter store for Key and ID storage.  Unless I can get the container to use the ECS role to act on its behalf outside.  

I just started with ECS so not sure yet
