### ISSUE TITLE
Compatibility Issue with Terraform v0.12.0 

### ISSUE THREAD

**Issue by edward8799** [camptocamp/terraboard#59]
Once I upgrade Terraform version to v0.12.0(provider.aws v2.10.0) and "terraform apply" to update state files, then state files disappear in the main dashboard page. Terraborad still can detect that those state files are v0.12.0 but won't display resources within the files. 
Could someone suggest, please?

**Comment by dimisjim** [comment]
@raphink Any plans to support 0.12?

**Comment by raphink** [comment]
@dimisjim 	Yes, this will probably go through terradb, when we find the time to work on it :smile:

**Comment by Erictsu1947** [comment]
any update on this issue?

thanks!

**Comment by raphink** [comment]
I haven't had time to work on it yet. If someone has pointers as to what changed in v0.12 that requires the update, that would be great!

**Comment by raphink** [comment]
Oh I see, `resources` are now directly at the root of the state file it seems, instead of being inside `modules`.

**Comment by Erictsu1947** [comment]
> I haven't had time to work on it yet. If someone has pointers as to what changed in v0.12 that requires the update, that would be great!

https://github.com/hashicorp/terraform/pull/18223

terraform on v0.12 change the state struct.

https://github.com/hashicorp/terraform/releases/tag/v0.12.0

official recommends to use `terraform show -json` instead of reading the content of state.

I will try to create a new pr on this, use parsing `terraform show` output

**Comment by raphink** [comment]
I'm working on refactoring it using `states/statefile` instead of `terraform/state`. See https://github.com/raphink/terraboard/tree/012

Current status: fighting with  `go-cty` to type the attributes properly…

**Comment by raphink** [comment]
I've opened a PR at https://github.com/camptocamp/terraboard/pull/62, which is still WIP, but you're welcome to test.

**Comment by fivehorizons** [comment]
> I've opened a PR at #62, which is still WIP, but you're welcome to test.

Does your fork require me to do docker-compose to build the image?    Do you have the image on dockerhub that I could grab?

**Comment by fivehorizons** [comment]
> I've opened a PR at #62, which is still WIP, but you're welcome to test.

Attempted to grab your repo go get.   Im getting some config.go errors associated with Sirupsen being changed to lowercase.    Your config.go does not reference it...

/root/go/src/github.com/camptocamp/terraboard/config/config.go:9:2: case-insensitive import collision: "github.com/sirupsen/logrus" and "github.com/Sirupsen/logrus"

**Comment by lucioveloso** [comment]
Awesome @raphink ! I created an image with your branch code and it worked. However, it's good to know that it just works with a new database. Using the previous database that already tried to load state from 0.12 does not work.

**Comment by fivehorizons** [comment]
@lucioveloso would you mind sharing the image?   Im dealing with corp firewall blocks on get pulls.

**Comment by lucioveloso** [comment]
I think that it's missing just the Activity column.

![image](https://user-images.githubusercontent.com/12705633/64541653-a0064a80-d2f8-11e9-9e5b-f5b73d28cb86.png)

**Comment by raphink** [comment]
Thanks for testing @fivehorizons  and @lucioveloso 	(and sorry for the my slow response). I'll check your comments soon (not today though I'm afraid).

**Comment by lucioveloso** [comment]
@fivehorizons you can try to use `lucioveloso/terraboard012:latest`.

**Comment by fivehorizons** [comment]
This is working great so far.    Up to terraform 0.12.7.    Seems the version included or downloaded needs to be replaced.     What is the easiest way to update the terraform binary to match latest version?

**Comment by dimisjim** [comment]
@lucioveloso It also detects state versions up to 0.12.6 for me : (

**Comment by fivehorizons** [comment]
@dimisjim  @lucioveloso  just need to mod the go,mod and change the terraform line to the following.  

`	github.com/hashicorp/terraform v0.12.9`

and then rebuild the image so it downloads new bits

**Comment by raphink** [comment]
I released v0.15.0 with support for Terraform 0.12
