### ISSUE TITLE
Terraboard unable to DNS look up DB on ECS

### ISSUE THREAD

**Issue by nema-sigsci** [camptocamp/terraboard#61]
# What I'm trying to do
Using ECS Fargate, I'm trying to run Terraboard and the Postgres DB in a single ECS task (two side by side containers). Terraboard fails to start since it cannot find the postgres db.

# What is failing
Terraboard attempts to dns lookup 'db' and fails since the postgres db isn't registered in the DNS, its not able to be looked up. 
> level=fatal msg="dial tcp: lookup db on 172.16.0.2:53: no such host"

Currently with ECS Fargate

# Expected behavior
Terraboard should try looking up `localhost` for the postgres db before fatally ending.

OR

There should be an ability to use hosted postgres (RDS) or a separate container/task.

**Comment by vibhuyadav** [comment]
I am also getting this error. Can we open the issue again?
