### ISSUE TITLE
Use S3 compatible bucket

### ISSUE THREAD

**Issue by rockyluke** [camptocamp/terraboard#72]
Hi,

First of all thank for developing terraboard, it's a really nice tool!

We are using our own _S3_ compatible system and currently I think can't change the address with `AWS_BUCKET` environment variable.

I would like to be able to use `AWS_BUCKET=s3://s3.offline.net/bucket_xxx`. Maybe I missed something but I think AWS addresses are deeply linked to aws-sdk-go.

**Comment by raphink** [comment]
Indeed, the current code only supports AWS S3 and the `AWS_BUCKET` parameter is the name of the bucket, not its address.

Supporting S3-compatible systems sounds like a good idea, though I'm not sure bucket versioning is available outside vanilla S3, and it is currently a hard requirement for Terraboard.

**Comment by rockyluke** [comment]
We are currently using https://ceph.io/planet/on-ceph-rgw-s3-object-versioning/ so AFIK it is supported!

**Comment by raphink** [comment]
OK then it's probably worth it to see if support can be added. Do you want to try and craft a PR?

**Comment by rockyluke** [comment]
I'll try to do my best but I am quite bad a go 😄

**Comment by raphink** [comment]
You can also contact me by email if you'd rather we work on that feature.

**Comment by rockyluke** [comment]
Mail sent. 🙏

**Comment by raphink** [comment]
@rockyluke I had a look at the implementation. Could you check if https://github.com/camptocamp/terraboard/pull/81 works for you?

**Comment by raphink** [comment]
This was implemented in #81
