### ISSUE TITLE
Terraform version in changelog

### ISSUE THREAD

**Issue by skycolangelom** [camptocamp/terraboard#73]
I have noticed that Terraboard can't read some of my tfstate files in my bucket. Logs are reporting that xxx.tfstate file has been created with a newer Terraform version that Terraboard can't support yet. 
It would be nice just to have some indications when putting a new image on DockerHub, saying what is the latest supported Terraform version. Thanks

**Comment by raphink** [comment]
Right, I've seen that as well. I will rebuild with the Terraform 0.12.20 libs and push a new version.

**Comment by raphink** [comment]
I'm adding a compat matrix to the README, see https://github.com/camptocamp/terraboard/pull/74. Would that do?

**Comment by raphink** [comment]
Added matrix in README and tf version in version string #75
