### ISSUE TITLE
pq sslmode

### ISSUE THREAD

**Issue by skycolangelom** [camptocamp/terraboard#76]
I've just tried to use latest version of Docker image (0.19.0) but I just can't connect to postgres:

level=fatal msg="pq: unsupported sslmode \"prefer\"; only \"require\" (default), \"verify-full\", \"verify-ca\", and \"disable\" supported"

Same behaviour with 0.18.0.

I've found a "sslmode" version on DockerHub and it's working fine.

Is it a regression? Or, can you point out how to manage sslmode on newer image versions?

**Comment by raphink** [comment]
Ah right, 0.18.0 added the possibility to set the `sslmode` for PostgreSQL (which was so far set to `disable`).

The default is set to `prefer` as it's the most sensible for security reason. However, it doesn't seem to work by default, for some reason (maybe gorm doesn't support it).

The options are:

* for now, set the SSLMODE to `disable` or `require` whether you want SSL or not (using `--db-sslmode=` or the `DB_SSLMODE` environment variable).
* maybe I should set the default back to `disable`, though I find this kind of ugly security-wise

**Comment by skycolangelom** [comment]
Thank you!

**Comment by ted-sigsci** [comment]
note the default of `prefer` fails for at least some versions of postgres RDS:
```
{
    "level": "fatal",
    "msg": "pq: unsupported sslmode \"prefer\"; only \"require\" (default), \"verify-full\", \"verify-ca\", and \"disable\" supported",
    "time": "2020-02-03T21:07:44Z"
}
```

I'll put in a PR to add the config option (from #70) to the README.

**Comment by tedder** [comment]
@raphink I think defaulting to prefer is a bad idea, [it's actually not supported by the golang pq package](https://github.com/camptocamp/terraboard/issues/76).

**Comment by raphink** [comment]
Ah, so that's the problem! I found it weird that recent PostgreSQL versions would not support it. I'm not very happy to default to `disable` again though, and forcing `require` is not a great option either…

**Comment by tedder** [comment]
I'd bias for "default to secure", if people want to downgrade it's a concious decision. But I understand either way.
