### ISSUE TITLE
 Terraboard container issue

### ISSUE THREAD

**Issue by younus2019** [camptocamp/terraboard#89]
while running Terraboard container It showing  "level=fatal msg="pq: SSL is not enabled on the server""
Please do the needful.

**Comment by younus2019** [comment]
Before running Terraboard container. i have ran the below command,
docker run --name db \
  -e POSTGRES_USER=gorm \
  -e POSTGRES_DB=gorm \
  -e POSTGRES_PASSWORD="user123" \
   --net terranet \
  --restart=always postgres

its showing 2020-04-21 08:18:25.773 UTC [1] LOG:  database system is ready to accept connections

**Comment by raphink** [comment]
If your PostgreSQL server does not support SSL, you need to pass `--db-sslmode=disable`

**Comment by younus2019** [comment]
thank you @raphink
