### ISSUE TITLE
Feat: Do not show sensitive values in UI

### ISSUE THREAD

**Issue by mhaley-miovision** [camptocamp/terraboard#99]
There are many cases where the output of a resource (or an input for that matter) will be marked as sensitive.  It would be nice if terraboard was able to recognize this and not display those sensitive values in the UI.

I have opened up https://github.com/hashicorp/terraform/issues/25646 to address the issue of this information not being in the state file.

**Comment by mhaley-miovision** [comment]
I think this is a legitimate feature request and should remain open. Terraform gives us the information we need to be able to implement this now.

**Comment by raphink** [comment]
I'm in favor of reopening. Do you want to propose a PR for it?
